### ISSUE TITLE
Non-Domain Machine Discovery Not Working

### ISSUE THREAD

**Issue by Deadcave** [thycotic/Discovery#24]
Hello,

I tested Non-Domain machine discovery script.
I can discover local account but I can't discover service accounts?
I tested Local Windows Service PS script but not working.
I ask to Thycotic this situation.
Thycotic answer: Script is incorrect.
Please help me.

Thanks.

**Comment by huzzeytech** [comment]
@Deadcave Could you confirm what you're trying to discover? A service running as a Local Windows Account or an AD Account?
Are you receiving an error?
Have you configured WinRM and CredSSP?

**Comment by Gartski** [comment]
I have this same problem also. WinRM/CredSSP are setup. The local account discovery finds the accounts but I don't find any dependencies. The service accounts are domain-joined as I really only used the script to be able to use an IP range.
