### ISSUE TITLE
WorkGroup Discovery, Access id Denied 

### ISSUE THREAD

**Issue by coolman128** [thycotic/Discovery#29]
Follow the instruction on thycotic server v.10.9, add new secret using Windows Accountbut hit below error.

```
Also go to  about_Remote_Troubleshooting Help topic (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_troubleshooting?view=powershell-7)
```

Tried Enable-PSRemoting, add TrustedHosts still the same issue, any idea ?
Tried administator, hostname\administrator

```
DiscoveryConsumer: Synchronizing Machines failed for [192.168.1.14]! Error: Connecting to remote server localhost failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
Attempting Powershell scan for machines.
Parameters are valid.
Starting scan..
Starting Script runner..
Finished Script runner using accountadministrator

Connecting to remote server localhost failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
```

**Comment by wsmelton** [comment]
> Connecting to remote server localhost failed with the following error message : Access is denied

This message indicates that Secret Server cannot start a PowerShell session either on the web node or Distributed Engine. You can review the Event Log for Windows to find out what account is trying to login to run the PowerShell script.

If you are using a Distributed Engine you can utilize the RunAs account for PowerShell configuration in your site settings. If you are not using a Distributed Engine add an account to the scanner that has the proper rights.
